## [作業重點]
使用 Sklearn 中的線性迴歸模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義

## 作業
試著使用 sklearn datasets 的其他資料集 (wine, boston, ...)，來訓練自己的線性迴歸模型。

### HINT: 注意 label 的型態，確定資料集的目標是分類還是回歸，在使用正確的模型訓練！

In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score
from sklearn.datasets import load_boston, load_wine

In [80]:
boston = datasets.load_boston()
print('--------------------------')
print(boston.data)
print('--------------------------')
print(boston['feature_names'])
print('--------------------------')
boston_2 = pd.DataFrame(boston['data'], columns = boston['feature_names'])


--------------------------
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
--------------------------
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
--------------------------


In [81]:
#整個資料集讀取近來的方法
boston_2 = pd.DataFrame(boston['data'], columns = boston['feature_names'])
boston_2.sample(10)

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
347   0.01870  85.0   4.15   0.0  0.429  6.516   27.7  8.5353   4.0  351.0   
225   0.52693   0.0   6.20   0.0  0.504  8.725   83.0  2.8944   8.0  307.0   
401  14.23620   0.0  18.10   0.0  0.693  6.343  100.0  1.5741  24.0  666.0   
240   0.11329  30.0   4.93   0.0  0.428  6.897   54.3  6.3361   6.0  300.0   
89    0.05302   0.0   3.41   0.0  0.489  7.079   63.1  3.4145   2.0  270.0   
265   0.76162  20.0   3.97   0.0  0.647  5.560   62.8  1.9865   5.0  264.0   
342   0.02498   0.0   1.89   0.0  0.518  6.540   59.7  6.2669   1.0  422.0   
20    1.25179   0.0   8.14   0.0  0.538  5.570   98.1  3.7979   4.0  307.0   
252   0.08221  22.0   5.86   0.0  0.431  6.957    6.8  8.9067   7.0  330.0   
367  13.52220   0.0  18.10   0.0  0.631  3.863  100.0  1.5106  24.0  666.0   

     PTRATIO       B  LSTAT  
347     17.9  392.43   6.36  
225     17.4  382.00   4.63  
401     20.2  396.90  20.32  
240     16.6  391.25  11.38  
89      17.8  396.06   5.70  
265     13.0  392.40  10.45  
342     15.9  389.96   8.65  
20      21.0  376.57  21.02  
252     19.1  386.09   3.53  
367     20.2  131.42  13.33

In [82]:
#無遺失值，皆為浮點數。
boston_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
dtypes: float64(13)
memory usage: 51.5 KB


In [83]:
# 讀取波士頓資料集
boston = datasets.load_boston()

# 為方便視覺化，我們只使用資料集中的 1 個 feature (column)
X = boston.data[:, np.newaxis, 6]
print("Data shape: ", X.shape) # 可以看見有 506 筆資料與我們取出的其中一個 feature

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(X, boston.target, test_size=0.1, random_state=4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

Data shape:  (506, 1)


In [84]:
# 讀取 Boston 資料
boston = load_boston()
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.1, random_state=4)

# 建立一個線性回歸模型
regr = LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [85]:
y_pred

array([11.46030778, 26.80269335, 17.43478925, 17.5563101 , 37.39156424,
       25.07675556, 31.05825852, 20.30845531, 19.66757374, 22.82655375,
       28.47083056, 28.53331605, 18.72883256, 33.11375161, 21.34282974,
       15.20554693, 21.57309275, 10.92841589, 11.69603405, 13.54311508,
        5.07126801, 17.40464043, 20.69379268, 22.72981238, 16.4634139 ,
       20.42666271, 17.53377349, 14.22644356, 21.56292745, 17.33136115,
       14.28888479, 23.92829804, 34.31523522, 22.03799035, 17.47895779,
       20.20386005, 30.70896335, 35.21599528, 24.07063567, 24.51445184,
       36.77425366, 33.15265201, 19.67545976, 31.93505104, 33.55222906,
       25.59147737, 40.59239607, 17.99555017, 19.92780188, 23.65319423,
       33.48950986])

In [86]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 17.04


In [92]:
a = datasets.load_wine()
a

a = datasets.load_wine()
print('--------------------------')
print(a.data)
print('--------------------------')
print(a['feature_names'])
print('--------------------------')
a_2 = pd.DataFrame(a['data'], columns = a['feature_names'])
print(a_2)
print(a_2.info())



--------------------------
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
--------------------------
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
--------------------------
     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0    

In [88]:
# 讀取 wine 資料
wine = load_wine()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.1, random_state=4)

# 建立一個羅吉斯回歸模型
regr = LogisticRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

/Users/squid504s/anaconda3/envs/sqenv/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/squid504s/anaconda3/envs/sqenv/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [89]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy: ", acc)

Accuracy:  0.9444444444444444
