資料參考來源：
https://morvanzhou.github.io/tutorials/data-manipulation/np-pd/2-4-np-math2/

### 基本示範

In [1]:
import numpy as np

In [4]:
array = np.array([[1,2,3],
                 [2,3,4]])
array

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
print('number of dim：', array.ndim ) #幾維
print('shape：', array.shape) #幾行幾列
print('size：', array.size) #多少資料

number of dim： 2
shape： (2, 3)
size： 6


### array創建

In [14]:
a = np.array([2,34,5], dtype = np.int) #要用列表創建, dtype指定資料型態, 一維
print(a)
print(a.dtype)

[ 2 34  5]
int64


In [15]:
b = np.array([[9,1,22],
              [32,11,5]]) #二維 三行兩列
print(b)

[[ 9  1 22]
 [32 11  5]]


In [36]:
c = np.zeros((3,4)) #創建4行3列的零矩陣
print(c)
print('________________________________')
d = np.ones((2,4), dtype = int) #1的矩陣
print(d)
print('________________________________')

e = np.empty((3,2)) #接近0的矩陣
print(e)
print('________________________________')

f = np.arange(14, 30, 2)  #類似range
print(f)
print('________________________________')

g = np.arange(12).reshape(3,4)  #重定義矩陣成4行3列
print(g)
print('________________________________')

h = np.linspace(1, 10, 4).reshape(2, 2) #在1~10中間有4段, 並為2行2列的矩陣。
print(h)
print('________________________________')


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
________________________________
[[1 1 1 1]
 [1 1 1 1]]
________________________________
[[1.08221785e-312 1.03977794e-312]
 [1.23075756e-312 1.06099790e-312]
 [1.12465777e-312 9.76118064e-313]]
________________________________
[14 16 18 20 22 24 26 28]
________________________________
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
________________________________
[[ 1.  4.]
 [ 7. 10.]]
________________________________


### numpy基本運算

In [44]:
a = np.array([10,20,30,4])
b = np.arange(4)
print(a, b)
print('________________________________')

c = a + b
print(c)
print('________________________________')

c = b**2
print(c)
print('________________________________')

c = 10*np.sin(a) #np.cos, np.tan
print(c)
print('________________________________')

print(b)
print(b<3) #b == 3, b>=3 ...等

[10 20 30  4] [0 1 2 3]
________________________________
[10 21 32  7]
________________________________
[0 1 4 9]
________________________________
[-5.44021111  9.12945251 -9.88031624 -7.56802495]
________________________________
[0 1 2 3]
[ True  True  True False]


In [61]:
#二維矩陣基本運算
a = np.array([[1,1],
              [8,3]])

b = np.arange(4).reshape(2,2)

print('array A:')
print(a)
print('array B:')
print(b)

c = a*b    #逐個相乘
c_dot = np.dot(a, b) #矩陣運算
c_dot2 = a.dot(b) #矩陣運算

print(c)
print(c_dot)
print(c_dot2)
print('________________________________')

a = np.random.random((2,4)) #0~1隨機生成 4行2列矩陣
print(a)
print(np.sum(a))
print(np.sum(a, axis = 1))
print('________________________________')

print(np.max(a))
print(np.max(a, axis = 1))
print('________________________________')

print(np.min(a))
print(np.min(a, axis = 0))

array A:
[[1 1]
 [8 3]]
array B:
[[0 1]
 [2 3]]
[[ 0  1]
 [16  9]]
[[ 2  4]
 [ 6 17]]
[[ 2  4]
 [ 6 17]]
________________________________
[[0.67655755 0.74730811 0.57076669 0.18959386]
 [0.16394513 0.38352128 0.0100781  0.44167113]]
3.183441841625144
[2.18422621 0.99921564]
________________________________
0.7473081067964954
[0.74730811 0.44167113]
________________________________
0.010078104920843822
[0.16394513 0.38352128 0.0100781  0.18959386]


### numpy 基礎運算2

In [78]:
a = np.arange(14, 2, -1).reshape((3,4)) 
print(a)
print('________________________________')
# array([[ 2, 3, 4, 5]
#        [ 6, 7, 8, 9]
#        [10,11,12,13]])
         
print(np.argmin(a))    # 最小值的index：0
print('________________________________')
print(np.argmax(a))    # 最大值的index：11
print('________________________________')
print(np.mean(a))
print('________________________________')
print(np.median(a))
print('________________________________')
print(np.cumsum(a))    #累加
print('________________________________')
print(np.diff(a))      #累差
print('________________________________')
print(np.nonzero(a))   #第幾行第幾列是非0的數
print('________________________________')
print(np.sort(a))   #逐列排序
print('________________________________')
print(np.transpose(a)) #行列轉換
print(a.T)
print((a.T).dot(a))
print('________________________________')
print(np.clip(a, 5, 9)) #小於5的數就等於5, 大於9的數就等於9, 5~9中間保持原形
print('________________________________')
print(np.mean(a, axis = 0))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
________________________________
11
________________________________
0
________________________________
8.5
________________________________
8.5
________________________________
[ 14  27  39  50  60  69  77  84  90  95  99 102]
________________________________
[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
________________________________
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
________________________________
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
________________________________
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]
________________________________
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
________________________________
[10.  9.  8.  7.]


### numpy索引(根據位置找到值及運算)

In [96]:
import numpy as np
a = np.arange(3, 15).reshape((3,4))
print(a)
print(a[2])
print('第二列第一行：', a[1][0]) 
print('第二列第一行：', a[1, 0])
print('第三列的所有數：',a[2, :])
print('第二列的第二跟第三個行的值：', a[1,1:3]) 

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
第二列第一行： 7
第二列第一行： 7
第三列的所有數： [11 12 13 14]
第二列的第二跟第三個行的值： [8 9]


In [104]:
#列迭代
for row in a:
    print(row)
  
print('-------------------------')
#行迭代，將矩陣轉置
for column in a.T:
    print(column)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
-------------------------
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [108]:
#迭代每個元素
#flat轉變為一列
print(A.flatten())

for item in a.flat:
    print(item)

[ 2  3  4  5  6  7  8  9 10 11 12 13]
3
4
5
6
7
8
9
10
11
12
13
14


### numpy array合併

In [132]:
import numpy as np
a = np.array([1,1,1])
b = np.array([2,2,2])
c = np.vstack((a,b))
d = np.hstack((a,b))
print('vertical stack:')
print(c)  #上下合併
print('horizontal stack:')
print(d)  #左右合併
print('-------------------------')
print('a:', a.shape, 'b:', b.shape, 'c:', c.shape, 'd:', d.shape)   #查行列
print('-------------------------')
print(a[np.newaxis, :].shape) #維度增加
print(a[:, np.newaxis].shape) #維度增加
print('-------------------------')
a2 = np.array([1,1,1])[:, np.newaxis]
b2 = np.array([2,2,2])[:, np.newaxis]
c2 = np.concatenate((a2 ,b2 ,b2 ,a2), axis = 1) #多個array縱向或橫向的合併 axis=0 上下合併 , axis = 1 左右合併
print(a2)
print('-------------------------')
print(b2)
print('-------------------------')
print(c2)

vertical stack:
[[1 1 1]
 [2 2 2]]
horizontal stack:
[1 1 1 2 2 2]
-------------------------
a: (3,) b: (3,) c: (2, 3) d: (6,)
-------------------------
(1, 3)
(3, 1)
-------------------------
[[1]
 [1]
 [1]]
-------------------------
[[2]
 [2]
 [2]]
-------------------------
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


### numpy array 分割

In [138]:
a = np.arange(12).reshape((3,4))
print(a)

print(np.split(a, 2, axis = 1))#縱向分割,分成兩塊
print(np.split(a, 3, axis = 0))#橫向分割,分成三塊

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [139]:
#不等量的分割
print(np.array_split(a, 3, axis = 1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [141]:
#橫向分割
print(np.vsplit(a, 3))

#縱向分割
print(np.hsplit(a, 2))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


### numpy array 賦值

In [150]:
a = np.arange(4)
print(a)

b = a
c = a
d = b
a[0] = 13
print(a)


[0 1 2 3]
[13  1  2  3]


a改變則其他都改變

In [156]:
b is a

True

In [154]:
c is a


True

In [155]:
d is b

True

In [157]:
d[1:3] = [22, 33]
d

array([13, 22, 33,  3])

In [158]:
a

array([13, 22, 33,  3])

In [159]:
b = a.copy() #deep copy 不想要跟其他有關聯
b

array([13, 22, 33,  3])